
HEADER = 64
PORT = 7777
FORMAT = 'utf-8'
DISCONNECT_MSG = '!DISCONNECT'
REQUEST_CPU = '!REQUEST_CPU'
REQUEST_MEM = '!REQUEST_MEM'
REQUEST_GATEWAY = '!REQUEST_GATEWAY'
REQUEST_NET = "!REQUEST_NET"
REQUEST_PID = "!REQUEST_PID"
REQUEST_DIR = "!REQUEST_DIR"
REQUEST_STAT = "!REQUEST_STAT"
REQUEST_SPACE = "!REQUEST_SPACE"
REQUEST_IP = "!REQUEST_IP"
REQUEST_FREQ = "REQUEST_FREQ"

BRANCO = (255, 255, 255)
PRETO = (0, 0, 0)
GREY = (20, 20, 20)
BTN_GREY = (230, 230, 230)
BACKGROUND_COLOR = (250, 250, 250)

LIST_INIT = 0
LIST_END = 22

